# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ed2e9ca7b1d3ae697ee88a1f8ed4976576ba51fdcd8e84330a6a24cdc209011d6479b0b1754bd4fb5e7a4814f23290691cca49d7a6b0d88fe54e01db5a82aaf3

test:
  secret_key_base: b9b461ecd8addf33795009a8f579b7f22c54b458beda608e2e4f656f3a39313d49289af12925c4fd2f883620b324a3f344ce8afb38e65942978fd8ffe0ecee4d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
